DATA_FOLDER_NAME = "data"
SANDBOX_FNAME = f"{DATA_FOLDER_NAME}/page_mappings.json"
POLL_DATA_FNAME = f"{DATA_FOLDER_NAME}/poll_data.json"
POLL_SUMMARY_FNAME = f"{DATA_FOLDER_NAME}/poll_summary.json"
POLL_DICTIONARY_FNAME = f"{DATA_FOLDER_NAME}/poll_dictionary.json"
